substitutions:
  name: esp-samsung-ac
  friendly_name: Klimatizace SAMSUNG

packages:
  common: !include templates/common.yaml

esp32:
  board: m5stack-atom



# AC CONFIGURATION  
uart:
  tx_pin: GPIO19
  rx_pin: GPIO22
  baud_rate: 9600
  parity: EVEN

external_components:
  - source: github://lanwin/esphome_samsung_ac@main
    components: [samsung_ac]

samsung_ac:
  # debug_log_messages: true
  # debug_log_messages_raw: true

  capabilities: 
    vertical_swing: true
    presets:
      sleep: true
      quiet: true
      fast: true
      longreach: true
      windfree: true

  devices:
    # BEDROOM
    - address: "20.00.00" # unit address

      # You could use the ESPHome/Homeassist climate control
      climate:
        name: "Klimatizace - ložnice"

      # And/or use seperate controls/sensors
      room_temperature:
        name: "Klimatizace - ložnice teplota"
      room_humidity:
        name: "Klimatizace - ložnice vlhkost"
      target_temperature:
        name: "Klimatizace - ložnice požadovaná teplota"
      power:
        name: "Klimatizace - ložnice vypínač"
      automatic_cleaning:
        name: "Klimatizace - ložnice automatické čištění"
    
    # LIVING ROOM
    - address: "20.00.01" # unit address

      # You could use the ESPHome/Homeassist climate control
      climate:
        name: "Klimatizace - obývák"

      # And/or use seperate controls/sensors
      room_temperature:
        name: "Klimatizace - obývák teplota"
      room_humidity:
        name: "Klimatizace - obývák vlhkost"
      target_temperature:
        name: "Klimatizace - obývák požadovaná teplota"
      power:
        name: "Klimatizace - obývák vypínač"
      automatic_cleaning:
        name: "Klimatizace - obývák automatické čištění"
      mode:
        name: "Klimatizace - obývák mód"
    
    # OUTDOOR UNIT
    - address: "10.00.00"
      outdoor_temperature:
        name: "Klimatizace - venkovní teplota"
      custom_sensor:
        - name: "Klimatizace - napětí"
          message: 0x24fc
          device_class: voltage
          state_class: measurement
          unit_of_measurement: V
        - name: "Klimatizace - proud"
          message: 0x8217
          device_class: current
          state_class: measurement
          unit_of_measurement: A
          accuracy_decimals: 1
          filters:
            - multiply: 0.1
        - name: "Klimatizace - výkon"
          message: 0x8413
          device_class: energy
          state_class: measurement
          unit_of_measurement: W
        - name: "Klimatizace - spotřeba"
          message: 0x8414
          device_class: energy
          state_class: total_increasing
          unit_of_measurement: kWh
          accuracy_decimals: 1
          filters:
            - multiply: 0.001



# DEVICE INFO
text_sensor:
  - platform: wifi_info
    ip_address:
      name: "${name} IP adresa"
      icon: mdi:ip-network

sensor:
  - platform: wifi_signal
    name: "${name} signál"
    update_interval: 10s
  
  - platform: uptime
    name: "${name} doba běhu"