<<: !include templates/template-esp-button-2g.yaml

# Configuration
substitutions:
  name: "esp-vypinac-loznice"

  switch1_single_press: svetlo_v_pracovne_klik
  switch1_double_press: svetlo_v_pracovne_dvojklik
  switch1_long_press: svetlo_v_pracovne_dlouhy_klik

  switch2_single_press: svetlo_v_loznici_klik
  switch2_double_press: svetlo_v_loznici_dvojklik
  switch2_long_press: svetlo_v_loznici_dlouhy_klik