# Configuration
substitutions:
  name: hasici

esphome:
  name: hasici
  platform: ESP32
  board: esp32-c3-devkitm-1
  on_boot:
    priority: -100
    then:
        - lambda: |-
            auto volume = 3*id(player_volume).state;
            id(player).set_volume(volume);
            ESP_LOGI("Boot", "Nastavuji hlasitost při startu na: %u", volume);

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  ap:
    ssid: "${name}.o"

logger:
  # baud_rate: 0

web_server:
  port: 80

ota:

api:

i2c:
  scl: GPIO8
  sda: GPIO9
  scan: false


uart:
  - id: uart_0
    tx_pin: GPIO21
    rx_pin: GPIO20
    baud_rate: 256000
    stop_bits: 1
    # debug:
    #     direction: BOTH
    #     dummy_receiver: true
    
  - id: uart_1
    tx_pin: GPIO7
    rx_pin: GPIO6
    baud_rate: 9600
    parity: NONE
    # debug:
    #     direction: BOTH
    #     dummy_receiver: true


# LED DIODY
light:
  - platform: neopixelbus
    variant: WS2812
    pin: GPIO2
    num_leds: 7
    type: GRB
    name: "Diody"
    id: diods
    effects:
      - strobe:
          name: Police Strobe
          colors:
            - state: True
              red: 100%
              green: 0%
              blue: 0%
              duration: 200ms
            - state: True
              red: 0%
              green: 0%
              blue: 100%
              duration: 200ms
      - addressable_color_wipe:
          name: Color Wipe Effect With Custom Values
          colors:
            - red: 100%
              green: 0%
              blue: 0%
              num_leds: 5
            - red: 0%
              green: 0%
              blue: 100%
              num_leds: 5
          add_led_interval: 50ms


# POHYBOVÝ SENZOR
ld2410:
  uart_id: uart_0


binary_sensor:
  - platform: ld2410
    has_target:
      id: ld2410_has_target
      name: Přítomnost
      on_press:
        - logger.log: "Přítomnost detekována"
        - lambda: |-
            auto time = id(my_time).now();
            if (id(my_time).now().is_valid() && time.month == 12 && time.day_of_month == 18) {
              ESP_LOGI("Birthday", "Všechno nejlepší!");
              auto call = id(diods).turn_on();
              call.set_brightness(1.0);
              call.set_rgb(1.0, 0.95, 0.70);
              call.perform();
            } else {
              id(play_button).press();
            }
      on_release:
        - logger.log: "Nikdo není přítomen"
        - light.turn_off:
            id: diods

    has_moving_target:
      name: Pohybující se objekt
      on_state:
        - logger.log: "Pohybující objekt detekován"
        
    has_still_target:
      name: Nepohybující se objekt
      on_state:
        - logger.log: "Nepohybující se objekt detekován"


# PŘEHRÁVÁČ
dfplayer:
  uart_id: uart_1
  id: player
  on_finished_playback:
    then:
      logger.log: 'Somebody press play!'


button:
  - platform: template
    name: "Spustit"
    icon: mdi:play
    id: play_button
    on_press:
      then:
        - lambda: |-
            int track = random(1, 4);
            id(player).play_mp3(track);
            ESP_LOGD("Player", "Spouštím skladbu: %d", track);
        - light.turn_on:
            id: diods
            effect: Police Strobe
        - delay: 15s
        - light.turn_off:  # Nejprve vypneme světlo
            id: diods
        - delay: 1s  # Krátké zpoždění, aby se zajistilo vypnutí
        - light.turn_on:  # Pak ho znovu zapneme s novou barvou
            id: diods
            brightness: 100%
            red: 100%
            green: 95%
            blue: 70%

  - platform: template
    name: "Zastavit"
    icon: mdi:pause
    id: pause_button
    on_press:
      then:
        - dfplayer.pause
        - light.turn_off:  # Nejprve vypneme světlo
            id: diods
        - delay: 1s  # Krátké zpoždění, aby se zajistilo vypnutí
        - if:
            condition:
              binary_sensor.is_on: ld2410_has_target
            then:
              - light.turn_on:  # Pak ho znovu zapneme s novou barvou, pokud je někdo přítomen
                  id: diods
                  brightness: 100%
                  red: 100%
                  green: 95%
                  blue: 70%
  

number:
  - platform: ld2410
    timeout:
      name: Čas detekce přítomnosti
      unit_of_measurement: s

    max_move_distance_gate:
      name: Maximální detekovaná zóna pro pohybující se cíl
    max_still_distance_gate:
      name: Maximální detekovaná zóna pro statický cíl
  - platform: template
    name: "Hlasitost"
    icon: mdi:volume-high
    id: player_volume
    min_value: 1
    max_value: 10
    restore_value: true
    initial_value: 5
    step: 1
    set_action:
      - lambda: |-
            int volume = 3*x;
            id(player).set_volume(volume);
            ESP_LOGD("Volume", "Nastavuji hlasitost na: %d", volume);


text_sensor:
  - platform: ld2410
    version:
      name: "firmware version"
    mac_address:
      name: "mac address"
  - platform: wifi_info
    ip_address:
      name: "IP adresa"
      icon: mdi:ip-network


sensor:
  - platform: ld2410
    detection_distance:
        name: Vzdálenost detekovaného objektu
  - platform: bmp280
    address: 0x76
    update_interval: 60s
    temperature:
      name: "Teplota v místnosti"
      oversampling: 16x
    pressure:
      name: "Tlak v místnosti"
  
  - platform: wifi_signal
    name: "WiFi signál"
    update_interval: 10s
  
  - platform: uptime
    name: "doba běhu"


time:
  - platform: sntp
    id: my_time