# Configuration
substitutions:
  name: hasici

esphome:
  name: hasici
  platform: ESP32
  board: esp32-c3-devkitm-1
  on_boot:
    priority: -100
    then:
        - lambda: |-
            auto volume = 3*id(player_volume).state;
            id(player).set_volume(volume);
            ESP_LOGI("Boot", "Nastavuji hlasitost při startu na: %u", volume);

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  ap:
    ssid: "${name}.o"

logger:
  # baud_rate: 0

web_server:
  port: 80
  version: 3
  log: false

ota:

api:

i2c:
  scl: GPIO8
  sda: GPIO9
  scan: false


uart:
  - id: uart_0
    tx_pin: GPIO21
    rx_pin: GPIO20
    baud_rate: 256000
    stop_bits: 1
    # debug:
    #     direction: BOTH
    #     dummy_receiver: true
    
  - id: uart_1
    tx_pin: GPIO7
    rx_pin: GPIO6
    baud_rate: 9600
    parity: NONE
    # debug:
    #     direction: BOTH
    #     dummy_receiver: true


# LED DIODY
light:
  - platform: neopixelbus
    variant: WS2812
    pin: GPIO2
    num_leds: 7
    type: GRB
    name: "Diody"
    id: diods
    restore_mode: RESTORE_DEFAULT_OFF
    effects:
      - strobe:
          name: Police Strobe
          colors:
            - state: True
              red: 100%
              green: 0%
              blue: 0%
              duration: 200ms
            - state: True
              red: 0%
              green: 0%
              blue: 100%
              duration: 200ms
      - addressable_color_wipe:
          name: Color Wipe Effect With Custom Values
          colors:
            - red: 100%
              green: 0%
              blue: 0%
              num_leds: 5
            - red: 0%
              green: 0%
              blue: 100%
              num_leds: 5
          add_led_interval: 50ms


# POHYBOVÝ SENZOR
ld2410:
  uart_id: uart_0


binary_sensor:
  - platform: status
    name: "Stav připojení"
    icon: mdi:lan-connect

  - platform: template
    name: "Stav přehrávání"
    id: dfplayer_playing
    icon: mdi:play-pause
    lambda: |-
      if (id(player).is_playing()) {
        return true;
      } else {
        return false;
      }

  - platform: ld2410
    has_target:
      id: ld2410_has_target
      name: Přítomnost
      on_press:
        - logger.log: "Přítomnost detekována"
        - lambda: |-
            auto time = id(my_time).now();
            if (time.is_valid() && time.month == 8 && time.day_of_month == 24) {
              id(birthday).press();
            } else {
              if (id(motion_sensor_active).state) {
                id(play_button).press();
              } else {
                id(photo_light).press();
              }
            }
      on_release:
        - logger.log: "Nikdo není přítomen"
        - light.turn_off:
            id: diods

    has_moving_target:
      name: Pohybující se objekt
      on_state:
        - logger.log: "Pohybující objekt detekován"
        
    has_still_target:
      name: Nepohybující se objekt
      on_state:
        - logger.log: "Nepohybující se objekt detekován"


# PŘEHRÁVÁČ
dfplayer:
  uart_id: uart_1
  id: player
  on_finished_playback:
    then:
      logger.log: 'Skončilo přehrávání'


switch:
  - platform: template
    name: "Pohybový senzor aktivní"
    icon: mdi:motion-sensor
    id: motion_sensor_active
    optimistic: true
    restore_mode: RESTORE_DEFAULT_ON
    entity_category: CONFIG
  
  - platform: template
    name: "06:00 - aktivní"
    icon: mdi:fire-alert
    id: time_6_00_active
    optimistic: true
    restore_mode: RESTORE_DEFAULT_ON
    entity_category: CONFIG

  - platform: template
    name: "06:58 - aktivní"
    icon: mdi:fire-alert
    id: time_6_58_active
    optimistic: true
    restore_mode: RESTORE_DEFAULT_ON
    entity_category: CONFIG

  - platform: template
    name: "07:00 - aktivní"
    icon: mdi:fire-alert
    id: time_7_00_active
    optimistic: true
    restore_mode: RESTORE_DEFAULT_ON
    entity_category: CONFIG

  - platform: template
    name: "12:00 - aktivní"
    icon: mdi:fire-alert
    id: time_12_00_active
    optimistic: true
    restore_mode: RESTORE_DEFAULT_ON
    entity_category: CONFIG

  - platform: template
    name: "12:30 - aktivní"
    icon: mdi:fire-alert
    id: time_12_30_active
    optimistic: true
    restore_mode: RESTORE_DEFAULT_ON
    entity_category: CONFIG

  - platform: template
    name: "15:30 - aktivní"
    icon: mdi:fire-alert
    id: time_15_30_active
    optimistic: true
    restore_mode: RESTORE_DEFAULT_ON
    entity_category: CONFIG

  - platform: template
    name: "17:00 - aktivní"
    icon: mdi:fire-alert
    id: time_17_00_active
    optimistic: true
    restore_mode: RESTORE_DEFAULT_ON
    entity_category: CONFIG

  - platform: template
    name: "22:00 - aktivní"
    icon: mdi:fire-alert
    id: time_22_00_active
    optimistic: true
    restore_mode: RESTORE_DEFAULT_ON
    entity_category: CONFIG

  - platform: template
    name: "23:00 - aktivní"
    icon: mdi:fire-alert
    id: time_23_00_active
    optimistic: true
    restore_mode: RESTORE_DEFAULT_ON
    entity_category: CONFIG


button:
  - platform: template
    name: "Spustit"
    icon: mdi:play
    id: play_button
    on_press:
      then:
        - lambda: |-
            int track = random(1, 5);
            id(player).play_folder(2, track);
            ESP_LOGD("Player", "Spouštím náhodnou hlášku: %d", track);
        - light.turn_on:
            id: diods
            brightness: !lambda |-
              return (id(brightness).state / 10.0);
            effect: Police Strobe
        - delay: 1s
        - wait_until:
            not:
              dfplayer.is_playing
        - light.turn_off:  # Nejprve vypneme světlo
            id: diods
        - delay: 1s  # Krátké zpoždění, aby se zajistilo vypnutí
        - if:
            condition:
              binary_sensor.is_on: ld2410_has_target
            then:
              - button.press: photo_light


  - platform: template
    name: "Narozeniny"
    icon: mdi:party-popper
    id: birthday
    #internal: true
    on_press:
      then:
        - lambda: |-
            id(player).play_folder(1, 1);
            ESP_LOGD("Player", "Spouštím přání k narozeninám");
        - light.turn_on:
            id: diods
            brightness: !lambda |-
              return (id(brightness).state / 10.0);
            effect: Police Strobe
        - delay: 1s
        - wait_until:
            not:
              dfplayer.is_playing
        - light.turn_off:
            id: diods
        - delay: 1s
        - if:
            condition:
              binary_sensor.is_on: ld2410_has_target
            then:
              - button.press: photo_light

  - platform: template
    name: "06:00 - budíček"
    icon: mdi:fire-alert
    id: time_trigger_6_00
    on_press:
      then:
        - lambda: |-
            id(player).play_folder(3, 1);
            ESP_LOGD("Player", "Spouštím budíček");
        - light.turn_on:
            id: diods
            brightness: !lambda |-
              return (id(brightness).state / 10.0);
            effect: Police Strobe
        - delay: 1s
        - wait_until:
            not:
              dfplayer.is_playing
        - light.turn_off:
            id: diods
        - delay: 1s
        - if:
            condition:
              binary_sensor.is_on: ld2410_has_target
            then:
              - button.press: photo_light

  - platform: template
    name: "06:58 - příprava střídání"
    icon: mdi:fire-alert
    id: time_trigger_6_58
    on_press:
      then:
        - lambda: |-
            id(player).play_folder(3, 2);
            ESP_LOGD("Player", "Spouštím příprava střídání");
        - light.turn_on:
            id: diods
            brightness: !lambda |-
              return (id(brightness).state / 10.0);
            effect: Police Strobe
        - delay: 1s
        - wait_until:
            not:
              dfplayer.is_playing
        - light.turn_off:
            id: diods
        - delay: 1s
        - if:
            condition:
              binary_sensor.is_on: ld2410_has_target
            then:
              - button.press: photo_light

  - platform: template
    name: "07:00 - střídání směn"
    icon: mdi:fire-alert
    id: time_trigger_7_00
    on_press:
      then:
        - lambda: |-
            id(player).play_folder(3, 3);
            ESP_LOGD("Player", "Spouštím střídání směn");
        - light.turn_on:
            id: diods
            brightness: !lambda |-
              return (id(brightness).state / 10.0);
            effect: Police Strobe
        - delay: 1s
        - wait_until:
            not:
              dfplayer.is_playing
        - light.turn_off:
            id: diods
        - delay: 1s
        - if:
            condition:
              binary_sensor.is_on: ld2410_has_target
            then:
              - button.press: photo_light

  - platform: template
    name: "12:00 - začátek polední přestávky"
    icon: mdi:fire-alert
    id: time_trigger_12_00
    on_press:
      then:
        - lambda: |-
            id(player).play_folder(3, 4);
            ESP_LOGD("Player", "Spouštím začátek polední přestávky");
        - light.turn_on:
            id: diods
            brightness: !lambda |-
              return (id(brightness).state / 10.0);
            effect: Police Strobe
        - delay: 1s
        - wait_until:
            not:
              dfplayer.is_playing
        - light.turn_off:
            id: diods
        - delay: 1s
        - if:
            condition:
              binary_sensor.is_on: ld2410_has_target
            then:
              - button.press: photo_light

  - platform: template
    name: "12:30 - konec polední přestávky"
    icon: mdi:fire-alert
    id: time_trigger_12_30
    on_press:
      then:
        - lambda: |-
            id(player).play_folder(3, 5);
            ESP_LOGD("Player", "Spouštím konec polední přestávky");
        - light.turn_on:
            id: diods
            brightness: !lambda |-
              return (id(brightness).state / 10.0);
            effect: Police Strobe
        - delay: 1s
        - wait_until:
            not:
              dfplayer.is_playing
        - light.turn_off:
            id: diods
        - delay: 1s
        - if:
            condition:
              binary_sensor.is_on: ld2410_has_target
            then:
              - button.press: photo_light

  - platform: template
    name: "15:30 - odpolední pauza"
    icon: mdi:fire-alert
    id: time_trigger_15_30
    on_press:
      then:
        - lambda: |-
            id(player).play_folder(3, 6);
            ESP_LOGD("Player", "Spouštím odpolední pauza");
        - light.turn_on:
            id: diods
            brightness: !lambda |-
              return (id(brightness).state / 10.0);
            effect: Police Strobe
        - delay: 1s
        - wait_until:
            not:
              dfplayer.is_playing
        - light.turn_off:
            id: diods
        - delay: 1s
        - if:
            condition:
              binary_sensor.is_on: ld2410_has_target
            then:
              - button.press: photo_light

  - platform: template
    name: "17:00 - večeře"
    icon: mdi:fire-alert
    id: time_trigger_17_00
    on_press:
      then:
        - lambda: |-
            id(player).play_folder(3, 7);
            ESP_LOGD("Player", "Spouštím večeře");
        - light.turn_on:
            id: diods
            brightness: !lambda |-
              return (id(brightness).state / 10.0);
            effect: Police Strobe
        - delay: 1s
        - wait_until:
            not:
              dfplayer.is_playing
        - light.turn_off:
            id: diods
        - delay: 1s
        - if:
            condition:
              binary_sensor.is_on: ld2410_has_target
            then:
              - button.press: photo_light

  - platform: template
    name: "22:00 - noční pohotovost"
    icon: mdi:fire-alert
    id: time_trigger_22_00
    on_press:
      then:
        - lambda: |-
            id(player).play_folder(3, 8);
            ESP_LOGD("Player", "Spouštím noční pohotovost");
        - light.turn_on:
            id: diods
            brightness: !lambda |-
              return (id(brightness).state / 10.0);
            effect: Police Strobe
        - delay: 1s
        - wait_until:
            not:
              dfplayer.is_playing
        - light.turn_off:
            id: diods
        - delay: 1s
        - if:
            condition:
              binary_sensor.is_on: ld2410_has_target
            then:
              - button.press: photo_light

  - platform: template
    name: "23:00 - druhý poločas"
    icon: mdi:fire-alert
    id: time_trigger_23_00
    on_press:
      then:
        - lambda: |-
            id(player).play_folder(3, 9);
            ESP_LOGD("Player", "Spouštím druhý poločas");
        - light.turn_on:
            id: diods
            brightness: !lambda |-
              return (id(brightness).state / 10.0);
            effect: Police Strobe
        - delay: 1s
        - wait_until:
            not:
              dfplayer.is_playing
        - light.turn_off:
            id: diods
        - delay: 1s
        - if:
            condition:
              binary_sensor.is_on: ld2410_has_target
            then:
              - button.press: photo_light

  - platform: template
    name: "Zastavit"
    icon: mdi:pause
    id: pause_button
    on_press:
      then:
        - dfplayer.stop
        - light.turn_off:  # Nejprve vypneme světlo
            id: diods
        - delay: 1s  # Krátké zpoždění, aby se zajistilo vypnutí
        - if:
            condition:
              binary_sensor.is_on: ld2410_has_target
            then:
              - button.press: photo_light

  - platform: template
    name: "Nasvítit fotku"
    icon: mdi:light-flood-down
    id: photo_light
    on_press:
      then:
        - light.turn_on:
            id: diods
            brightness: !lambda |-
              return (id(brightness).state / 10.0);
            red: 100%
            green: 95%
            blue: 70%

number:
  - platform: ld2410
    timeout:
      name: Čas detekce přítomnosti
      unit_of_measurement: s

    max_move_distance_gate:
      name: Maximální detekovaná zóna pro pohybující se cíl
    max_still_distance_gate:
      name: Maximální detekovaná zóna pro statický cíl
  
  - platform: template
    name: "Hlasitost"
    icon: mdi:volume-high
    id: player_volume
    entity_category: config
    min_value: 1
    max_value: 10
    restore_value: true
    initial_value: 5
    step: 1
    set_action:
      - lambda: |-
            int volume = 3*x;
            id(player).set_volume(volume);
            ESP_LOGD("Volume", "Nastavuji hlasitost na: %d", volume);

  - platform: template
    name: "Jas"
    icon: mdi:brightness-4
    id: brightness
    entity_category: config
    min_value: 1
    max_value: 10
    restore_value: true
    initial_value: 10
    step: 1
    set_action:
      - if:
          condition:
            light.is_on: diods
          then:
            - lambda: |-
                int brightness_value = x;
                auto call = id(diods).turn_on();
                call.set_brightness(brightness_value / 10.0);
                call.perform();
                ESP_LOGD("Brightness", "Nastavuji jas na: %d%%", brightness_value);


text_sensor:
  - platform: ld2410
    version:
      name: "firmware version"
    mac_address:
      name: "mac address"
  - platform: wifi_info
    ip_address:
      name: "IP adresa"
      icon: mdi:ip-network


sensor:
  - platform: ld2410
    detection_distance:
        name: Vzdálenost detekovaného objektu
  
  - platform: bmp280
    address: 0x76
    update_interval: 60s
    temperature:
      name: "Teplota v místnosti"
      oversampling: 16x
    pressure:
      name: "Tlak v místnosti"
  
  - platform: wifi_signal
    name: "WiFi signál"
    update_interval: 10s
  
  - platform: uptime
    name: "doba běhu"


time:
  - platform: sntp
    id: my_time
    on_time:
      - seconds: 0
        minutes: 0
        hours: 6
        then:
          - lambda: |-
              auto time = id(my_time).now();
              if (time.is_valid() && id(time_6_00_active).state && (id(ld2410_has_target).state || !id(motion_sensor_active).state)) {
                ESP_LOGI("Time", "Je 6:00, provádím akci.");
                id(time_trigger_6_00).press();
              }
      
      - seconds: 0
        minutes: 58
        hours: 6
        then:
          - lambda: |-
              auto time = id(my_time).now();
              if (time.is_valid() && id(time_6_58_active).state && (id(ld2410_has_target).state || !id(motion_sensor_active).state)) {
                ESP_LOGI("Time", "Je 6:58, provádím akci.");
                id(time_trigger_6_58).press();
              }
      
      - seconds: 0
        minutes: 0
        hours: 7
        then:
          - lambda: |-
              auto time = id(my_time).now();
              if (time.is_valid() && id(time_7_00_active).state && (id(ld2410_has_target).state || !id(motion_sensor_active).state)) {
                ESP_LOGI("Time", "Je 7:00, provádím akci.");
                id(time_trigger_7_00).press();
              }
      
      - seconds: 0
        minutes: 0
        hours: 12
        then:
          - lambda: |-
              auto time = id(my_time).now();
              if (time.is_valid() && id(time_12_00_active).state && (id(ld2410_has_target).state || !id(motion_sensor_active).state)) {
                ESP_LOGI("Time", "Je 12:00, provádím akci.");
                id(time_trigger_12_00).press();
              }

      - seconds: 0
        minutes: 30
        hours: 12
        then:
          - lambda: |-
              auto time = id(my_time).now();
              if (time.is_valid() && id(time_12_30_active).state && (id(ld2410_has_target).state || !id(motion_sensor_active).state)) {
                ESP_LOGI("Time", "Je 12:30, provádím akci.");
                id(time_trigger_12_30).press();
              }

      - seconds: 0
        minutes: 30
        hours: 15
        then:
          - lambda: |-
              auto time = id(my_time).now();
              if (time.is_valid() && id(time_15_30_active).state && (id(ld2410_has_target).state || !id(motion_sensor_active).state)) {
                ESP_LOGI("Time", "Je 15:30, provádím akci.");
                id(time_trigger_15_30).press();
              }

      - seconds: 0
        minutes: 00
        hours: 17
        then:
          - lambda: |-
              auto time = id(my_time).now();
              if (time.is_valid() && id(time_17_00_active).state && (id(ld2410_has_target).state || !id(motion_sensor_active).state)) {
                ESP_LOGI("Time", "Je 17:00, provádím akci.");
                id(time_trigger_17_00).press();
              }

      - seconds: 0
        minutes: 29
        hours: 20
        then:
          - lambda: |-
              auto time = id(my_time).now();
              if (time.is_valid() && id(time_22_00_active).state && (id(ld2410_has_target).state || !id(motion_sensor_active).state)) {
                ESP_LOGI("Time", "Je 22:00, provádím akci.");
                id(time_trigger_22_00).press();
              }
      
      - seconds: 0
        minutes: 00
        hours: 23
        then:
          - lambda: |-
              auto time = id(my_time).now();
              if (time.is_valid() && id(time_23_00_active).state && (id(ld2410_has_target).state || !id(motion_sensor_active).state)) {
                ESP_LOGI("Time", "Je 23:00, provádím akci.");
                id(time_trigger_23_00).press();
              }