# Configuration
substitutions:
  name: esp-vypinac-chodba
  friendly_name: Vypínač - chodba

packages:
  common: !include templates/template-esp-sonoff-dual-r3-event.yaml
  bluetooth-proxy: !include templates/bluetooth-proxy.yaml