substitutions:
  name: esp-garage-door
  # Higher value gives lower watt readout
  current_res: "0.001"
  # Lower value gives lower voltage readout
  voltage_div: "1925"

esphome:
  name: ${name}
  platformio_options:
    board_build.f_cpu: 160000000L

esp32:
  board: esp32doit-devkit-v1
  framework:
    type: esp-idf
    sdkconfig_options:
      CONFIG_FREERTOS_UNICORE: y
      CONFIG_ESP32_DEFAULT_CPU_FREQ_160: y
      CONFIG_ESP32_DEFAULT_CPU_FREQ_MHZ: "160"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  
  ap:
    ssid: "${name}.o"
    password: !secret esp_home_fallback_wifi_password

captive_portal:

logger:

api:
  encryption:
    key: !secret esp_home_api_password

ota:
  password: !secret esp_home_ota_password

output:
  - platform: gpio
    id: "relay_output"
    pin: GPIO26

switch:
  - platform: output
    id: "relay"
    name: "${name} relé"
    output: "relay_output"
    internal: true

button:
  - platform: template
    name: "${name} vrata od garáže"
    icon: mdi:garage
    id: garage_button
    on_press:
      - switch.turn_off: relay
      - switch.turn_on: relay
      - delay: 0.1s
      - switch.turn_off: relay

status_led:
  pin:
    number: GPIO0
    inverted: true

text_sensor:
  - platform: wifi_info
    ip_address:
      name: "${name} IP adresa"
      icon: mdi:ip-network

binary_sensor:
  - platform: gpio
    name: "${name} vypínač"
    pin: GPIO4
    on_press:
      then:
        - switch.toggle: "relay"
    filters:
      - delayed_on_off: 50ms
  
  - platform: gpio
    name: "${name} tlačítko"
    pin:
      number: GPIO25
      inverted: yes
      mode:
        input: true
        pullup: true
    on_press:
      then:
        - switch.turn_off: relay
        - switch.turn_on: relay
        - delay: 0.1s
        - switch.turn_off: relay
    filters:
      - delayed_on_off: 5ms

  - platform: status
    name: "${name} připojení k HA"
    id: connection_to_ha

sensor:
  - platform: ntc
    sensor: temp_resistance_reading
    name: "${name} teplota zařízení"
    entity_category: diagnostic
    unit_of_measurement: "°C"
    accuracy_decimals: 1
    icon: "mdi:thermometer"
    calibration:
      b_constant: 3350
      reference_resistance: 10kOhm
      reference_temperature: 298.15K
    on_value_range:
      - above: "80.0"
        then:
          - switch.turn_off: "relay"

  - platform: resistance
    id: temp_resistance_reading
    sensor: temp_analog_reading
    configuration: DOWNSTREAM
    resistor: 10kOhm

  - platform: adc
    id: temp_analog_reading
    pin: GPIO32
    attenuation: 11db

  - platform: adc
    name: "${name} napětí zdroje relé"
    entity_category: diagnostic
    pin: GPIO33
    attenuation: 11db
    filters:
      - multiply: 8

  - platform: wifi_signal
    name: "${name} signál"
    update_interval: 10s
  
  - platform: uptime
    name: "${name} doba běhu"