substitutions:
    name: esp-door-bell

esphome:
    name: ${name}
  
esp32:
    board: nodemcu-32s
  
# Enable logging
logger:
    #Turn off RX TX
    baud_rate: 0
  
# Enable Home Assistant API
api:
    encryption:
        key: !secret esp_home_api_password

ota:
    password: !secret esp_home_ota_password

wifi:
    ssid: !secret wifi_ssid
    password: !secret wifi_password

    # Enable fallback hotspot (captive portal) in case wifi connection fails
    ap:
        ssid: "${name}.o"
        password: !secret esp_home_fallback_wifi_password

captive_portal:


binary_sensor:
    - platform: gpio
      name: "${name} tlačítko"
      icon: mdi:gesture-tap-button
      id: button
      pin:
        number: GPIO33
        mode: INPUT_PULLUP
        inverted: true
      on_click: 
        then:
          - homeassistant.service:
              service: script.turn_on
              data:
                entity_id: script.zvonek_u_dveri
          - light.toggle: led
          - delay: 500ms
          - light.toggle: led
          - delay: 500ms
          - light.toggle: led
          - delay: 500ms
          - light.toggle: led
          - delay: 500ms
          - light.toggle: led
          - delay: 500ms
          - light.toggle: led
          - delay: 500ms
          - light.toggle: led
          - delay: 500ms
          - light.toggle: led
          - delay: 500ms

light:
    - platform: binary
      id: led
      name: "${name} LED"
      icon: mdi:led-on
      output: led_output

output:
    - id: led_output
      platform: gpio
      pin: GPIO32