substitutions:
  name: esp-klimatizace
  friendly_name: Klimatizace

packages:
  common: github://bzumik1/HomeAssistant/EspHome/templates/common.yaml@main

esp32:
  board: m5stack-atom

# AC CONFIGURATION  
uart:
  tx_pin: GPIO19
  rx_pin: GPIO22
  baud_rate: 9600
  parity: EVEN

external_components:
  - source: github://omerfaruk-aran/esphome_samsung_hvac_bus@main
    components: [samsung_ac]

samsung_ac:
  # debug_log_messages: true
  # debug_log_messages_raw: true

  capabilities: 
    vertical_swing: true
    presets:
      sleep: true
      quiet: true
      fast: true
      longreach: true
      windfree: true
      eco: true

  devices:
    # BEDROOM
    - address: "20.00.00" # unit address
      error_code:
        name: "ložnice error"

      # You could use the ESPHome/Homeassist climate control
      climate:
        name: "ložnice"

      # And/or use seperate controls/sensors
      # room_temperature:
      #   name: "ložnice teplota"
      # room_humidity:
      #   name: "ložnice vlhkost"
      # target_temperature:
      #   name: "ložnice požadovaná teplota"
      # power:
      #   name: "ložnice vypínač"
      automatic_cleaning:
        name: "ložnice automatické čištění"
        icon: mdi:broom
      # mode:
      #   name: "ložnice mód"
    
    # LIVING ROOM
    - address: "20.00.01" # unit address
      error_code:
        name: "obývák error"

      # You could use the ESPHome/Homeassist climate control
      climate:
        name: "obývák"

      # And/or use seperate controls/sensors
      # room_temperature:
      #   name: "obývák teplota"
      # room_humidity:
      #   name: "obývák vlhkost"
      # target_temperature:
      #   name: "obývák požadovaná teplota"
      # power:
      #   name: "obývák vypínač"
      automatic_cleaning:
        name: "obývák automatické čištění"
        icon: mdi:broom
      # mode:
      #   name: "obývák mód"
    
    # OUTDOOR UNIT
    - address: "10.00.00"
      error_code:
        name: "venkovní jednotka error"
      outdoor_temperature:
        name: "venkovní teplota"
      outdoor_instantaneous_power:
        name: "aktuální výkon"
      outdoor_cumulative_energy:
        name: "celková spotřeba"
      outdoor_current:
        name: "proud"
      outdoor_voltage:
        name: "napětí"