# Configuration
substitutions:
  name: "esp-vypinac-koupelna"
  friendly_name: "Vypínač - koupelna"

packages:
  sonoff-template: github://bzumik1/HomeAssistant/EspHome/templates/template-esp-sonoff-dual-r3-event.yaml@main
  bluetooth-proxy: github://bzumik1/HomeAssistant/EspHome/templates/bluetooth-proxy.yaml@main