# Configuration
substitutions:
  name: "esp-vypinac-zaluzie-obyvak"
  friendly_name: "Vypínač - žaluzie obývák"
  # Relay trip limits
  max_power: "3600.0"
  max_temp: "95.0"

packages:
  shelly-template: github://bzumik1/HomeAssistant/EspHome/templates/template-esp-shelly-2pm-event.yaml@main
  bluetooth-proxy: github://bzumik1/HomeAssistant/EspHome/templates/bluetooth-proxy.yaml@main