# Configuration
substitutions:
  name: "esp-svetlo-10"
  friendly_name: "Světlo - 10"
  light_1_name: "světlo 10a"
  light_2_name: "světlo 10b"
  cold_white_color_temperature: "6500 K"
  warm_white_color_temperature: "2700 K"

packages:
  penta-plus-template: !include ../templates/template-esp-an-penta-plus-wired-dual-light.yaml
