# Configuration
substitutions:
  name: "esp-zaluzie-loznice-1"
  friendly_name: "Žaluzie - ložnice 1"

packages:
  cover-template: !include ../templates/template-esp-sonoff-dual-r3-cover.yaml

wifi:
  use_address: esp-sonoff-dual-r3-1.local
