# Configuration
substitutions:
  name: "esp-zaluzie-horni-loznice"
  friendly_name: "Žaluzie - horní ložnice"

packages:
  cover-template: !include ../templates/template-esp-sonoff-dual-r3-cover.yaml
