# Configuration
substitutions:
  name: "esp-svetlo-01"
  friendly_name: "Světlo - 01"
  light_1_name: "světlo 1a"
  light_2_name: "světlo 1b"
  cold_white_color_temperature: "6500 K"
  warm_white_color_temperature: "2200 K"

packages:
  penta-mini-template: !include ../templates/template-esp-an-penta-mini-wired-dual-light.yaml