# Configuration
substitutions:
  name: "esp-zaluzie-loznice-2"
  friendly_name: "Žaluzie - ložnice 2"

packages:
  cover-template: !include ../templates/template-esp-sonoff-dual-r3-cover.yaml

wifi:
  use_address: esp-sonoff-dual-r3-2.local
