# Configuration
substitutions:
  name: "esp-zaluzie-detsky-pokoj-1"
  friendly_name: "Žaluzie - dětský pokoj 1"

packages:
  cover-template: !include ../templates/template-esp-sonoff-dual-r3-cover.yaml
