esphome:
  name: ${name}

esp8266:
  board: esp8285
  restore_from_flash: true

# Enable logging
logger:
  #Turn off RX TX
  baud_rate: 0

# Enable Home Assistant API
api:
  encryption:
    key: !secret esp_home_api_password

ota:
  password: !secret esp_home_ota_password

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "${name}.o"
    password: !secret esp_home_fallback_wifi_password

captive_portal:

button:
  - platform: factory_reset
    name: Resetování do továrního nastavení
    id: reset

output:
  - platform: gpio
    pin: GPIO4
    id: relay1
  - platform: gpio
    pin: GPIO5
    id: relay2

light:
  - platform: status_led
    name: "${name} stavová LED"
    icon: mdi:led-on
    pin:
      number: GPIO12
      inverted: true

  - platform: binary
    name: "${name} světlo 1"
    icon: mdi:ceiling-light-multiple
    id: light1
    output: relay1
    restore_mode: RESTORE_DEFAULT_OFF
  
  - platform: binary
    name: "${name} světlo 2"
    icon: mdi:ceiling-light-multiple
    id: light2
    output: relay2
    restore_mode: RESTORE_DEFAULT_OFF

binary_sensor:
  # Wired switch 1
  - platform: gpio
    name: "${name} vypínač 1"
    icon: mdi:light-switch
    id: the_switch_1
    pin:
      number: GPIO1
      mode: INPUT_PULLUP
      inverted: true
    on_state:
      - light.toggle: light1

  # Wired switch
  - platform: gpio
    name: "${name} vypínač 2"
    icon: mdi:light-switch
    id: the_switch_2
    pin:
      number: GPIO3
      mode: INPUT_PULLUP
      inverted: true
    on_state:
      - light.toggle: light2

  # Button on mini switch
  - platform: gpio
    name: "${name} tlačítko"
    icon: mdi:gesture-tap-button
    pin:
      number: GPIO14
      mode: INPUT_PULLUP
      inverted: true
    on_multi_click:
      - timing:
          - ON for at most 1s
          - OFF for at least 0.2s
        then:
          - light.toggle: light1
          - light.toggle: light2
      - timing:
          - ON for at least 4s
        then:
          - button.press: reset

  - platform: status
    name: "${name} stav"

text_sensor:
  - platform: wifi_info
    ip_address:
      name: "${name} IP adresa"
      icon: mdi:ip-network

sensor:
  - platform: wifi_signal
    name: "${name} signál"
    update_interval: 10s
  
  - platform: uptime
    name: "${name} doba běhu"

time:
  - platform: sntp
    id: my_time