esphome:
  name: ${name}

esp32:
  board: esp32dev

logger:
  level: INFO

# Enable Home Assistant API
api:
  encryption:
    key: !secret esp_home_api_password

ota:
  password: !secret esp_home_ota_password

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "${name}.o"
    password: !secret esp_home_fallback_wifi_password

captive_portal:

uart:
  tx_pin: GPIO25
  rx_pin: GPIO26
  baud_rate: 4800
  parity: NONE
  stop_bits: 2

output:
  - platform: gpio
    pin: GPIO27
    id: relay1
  - platform: gpio
    pin: GPIO14
    id: relay2

switch:
  - platform: output
    name: "${name} relé 1"
    icon: mdi:toggle-switch-variant
    restore_mode: RESTORE_DEFAULT_ON
    output: relay1
    id: switch_relay1
  - platform: output
    name: "${name} relé 2"
    icon: mdi:toggle-switch-variant
    restore_mode: RESTORE_DEFAULT_ON
    output: relay2
    id: switch_relay2

light:
  - platform: status_led
    name: "${name} stavová LED"
    id: led_status
    icon: mdi:led-on
    entity_category: config
    pin:
      number: GPIO13
      inverted: True
    internal: True

binary_sensor:
  # Connection to HA
  - platform: status
    name: "${name} připojení k HA"
    id: connection_to_ha

  # Wired switch 1
  - platform: gpio
    name: "${name} vypínač 1"
    icon: mdi:light-switch
    id: the_switch_1
    pin:
      number: GPIO32
      mode: INPUT_PULLUP
      inverted: true
    on_multi_click:
      # Single press
      - timing:
          - ON for at most 400ms
          - OFF for at least 210ms
        then:
          - if:
              condition:
                binary_sensor.is_off: connection_to_ha
              then:
                - switch.toggle: switch_relay1
              else:
                - homeassistant.service:
                    service: script.turn_on
                    data:
                      entity_id: script.${switch1_single_press}
      # Double press
      - timing:
        - ON for at most 400ms
        - OFF for at most 200ms
        - ON for at most 400ms
        - OFF for at least 200ms
        then:
          - homeassistant.service:
              service: script.turn_on
              data:
                entity_id: script.${switch1_double_press}
      # Long press
      - timing:
        - ON for at least 500ms
        then:
          - homeassistant.service:
              service: script.turn_on
              data:
                entity_id: script.${switch1_long_press}
      # Relay toggle
      - timing:
          - ON for at least 1500ms
        then:
          - switch.toggle: switch_relay1

  # Wired switch 2
  - platform: gpio
    name: "${name} vypínač 2"
    icon: mdi:light-switch
    id: the_switch_2
    pin:
      number: GPIO33
      mode: INPUT_PULLUP
      inverted: true
    on_multi_click:
      # Single press
      - timing:
          - ON for at most 400ms
          - OFF for at least 210ms
        then:
          - if:
              condition:
                binary_sensor.is_off: connection_to_ha
              then:
                - switch.toggle: switch_relay2
              else:
                - homeassistant.service:
                    service: script.turn_on
                    data:
                      entity_id: script.${switch2_single_press}
      # Double press
      - timing:
        - ON for at most 400ms
        - OFF for at most 200ms
        - ON for at most 400ms
        - OFF for at least 200ms
        then:
          - homeassistant.service:
              service: script.turn_on
              data:
                entity_id: script.${switch2_double_press}
      # Long press
      - timing:
        - ON for at least 500ms
        then:
          - homeassistant.service:
              service: script.turn_on
              data:
                entity_id: script.${switch2_long_press}
      # Relay toggle
      - timing:
          - ON for at least 1500ms
        then:
          - switch.toggle: switch_relay2

  # Button on mini switch
  - platform: gpio
    name: "${name} tlačítko"
    icon: mdi:gesture-tap-button
    pin:
      number: GPIO00
      mode: INPUT_PULLUP
      inverted: true
    filters:
      - delayed_on: 50ms
    on_multi_click:
      - timing:
          - ON for at most 1s
          - OFF for at least 0.2s
        then:
          - switch.toggle: switch_relay1
          - switch.toggle: switch_relay2

button:
  - platform: restart
    name: "${name} restartování"

text_sensor:
  - platform: wifi_info
    ip_address:
      name: "${name} IP adresa"
      icon: mdi:ip-network

sensor:
  - platform: bl0939
    update_interval: 10s
    voltage:
      name: "${name} napětí"
    current_1:
      name: "${name} proud 1"
      disabled_by_default: True
    current_2:
      name: "${name} proud 2"
      disabled_by_default: True
    active_power_1:
      name: "${name} výkon 1"
    active_power_2:
      name: "${name} výkon 2"
    energy_1:
      name: "${name} spotřeba 1"
    energy_2:
      name: "${name} spotřeba 2"
    energy_total:
      name: "${name} spotřeba celkem"

  - platform: wifi_signal
    name: "${name} signál"
    update_interval: 10s
  
  - platform: uptime
    name: "${name} doba běhu"

time:
  - platform: sntp
    id: my_time