substitutions:
  measurement_interval: 1s

packages:
  common: !include common.yaml

esp32_improv:
  authorizer: none
  wifi_timeout: 5min

esp32:
  board: esp32dev


uart:
  tx_pin: GPIO25
  rx_pin: GPIO26
  baud_rate: 4800
  parity: NONE
  stop_bits: 2


output:
  - platform: gpio
    pin: GPIO27
    id: relay1

  - platform: gpio
    pin: GPIO14
    id: relay2


switch:
  - platform: output
    name: "relé 1"
    icon: mdi:toggle-switch-variant
    restore_mode: RESTORE_DEFAULT_ON
    output: relay1
    id: switch_relay1

  - platform: output
    name: "relé 2"
    icon: mdi:toggle-switch-variant
    restore_mode: RESTORE_DEFAULT_ON
    output: relay2
    id: switch_relay2


light:
  - platform: status_led
    name: "stavová LED"
    id: led_status
    icon: mdi:led-on
    entity_category: config
    pin:
      number: GPIO13
      inverted: True
    internal: True


binary_sensor:

  # Wired switch 1
  - platform: gpio
    name: "vypínač 1"
    icon: mdi:light-switch
    id: the_switch_1
    pin:
      number: GPIO32
      mode: INPUT_PULLUP
      inverted: true
    on_multi_click:
      # Single press
      - timing:
          - ON for at most 400ms
          - OFF for at least 210ms
        then:
          - if:
              condition:
                binary_sensor.is_off: connection_to_ha
              then:
                - switch.toggle: switch_relay1
              else:
                - switch.turn_on: switch_relay1
                - homeassistant.event:
                    event: esphome.${name}_switch1_single_press
      # Double press
      - timing:
        - ON for at most 400ms
        - OFF for at most 200ms
        - ON for at most 400ms
        - OFF for at least 200ms
        then:
          - homeassistant.event:
              event: esphome.${name}_switch1_double_press
      # Long press
      - timing:
        - ON for at least 500ms
        then:
          - homeassistant.event:
              event: esphome.${name}_switch1_long_press
      # Relay toggle
      - timing:
          - ON for at least 1500ms
        then:
          - switch.toggle: switch_relay1

  # Wired switch 2
  - platform: gpio
    name: "vypínač 2"
    icon: mdi:light-switch
    id: the_switch_2
    pin:
      number: GPIO33
      mode: INPUT_PULLUP
      inverted: true
    on_multi_click:
      # Single press
      - timing:
          - ON for at most 400ms
          - OFF for at least 210ms
        then:
          - if:
              condition:
                binary_sensor.is_off: connection_to_ha
              then:
                - switch.toggle: switch_relay2
              else:
                - switch.turn_on: switch_relay2
                - homeassistant.event:
                    event: esphome.${name}_switch2_single_press
      # Double press
      - timing:
        - ON for at most 400ms
        - OFF for at most 200ms
        - ON for at most 400ms
        - OFF for at least 200ms
        then:
          - homeassistant.event:
              event: esphome.${name}_switch2_double_press
      # Long press
      - timing:
        - ON for at least 500ms
        then:
          - homeassistant.event:
              event: esphome.${name}_switch2_long_press
      # Relay toggle
      - timing:
          - ON for at least 1500ms
        then:
          - switch.toggle: switch_relay2

  # Button on mini switch
  - platform: gpio
    name: "tlačítko"
    icon: mdi:gesture-tap-button
    pin:
      number: GPIO00
      mode: INPUT_PULLUP
      inverted: true
    filters:
      - delayed_on: 50ms
    on_multi_click:
      - timing:
          - ON for at most 1s
          - OFF for at least 0.2s
        then:
          - switch.toggle: switch_relay1
          - switch.toggle: switch_relay2

sensor:
  - platform: bl0939
    update_interval: ${measurement_interval}
    voltage:
      name: "napětí"
    current_1:
      name: "proud 1"
      id: current_1
    current_2:
      name: "proud 2"
      id: current_2
    active_power_1:
      name: "výkon 1"
      id: active_power_1
    active_power_2:
      name: "výkon 2"
      id: active_power_2
    energy_1:
      name: "spotřeba 1"
      icon: mdi:counter
    energy_2:
      name: "spotřeba 2"
      icon: mdi:counter
    energy_total:
      name: "spotřeba celkem"
      icon: mdi:counter

  - platform: template
    name: "výkon celkem"
    icon: mdi:lightning-bolt
    unit_of_measurement: "W"
    lambda: |-
      return id(active_power_1).state + id(active_power_2).state;
    update_interval: ${measurement_interval}

  - platform: template
    name: "proud celkem"
    icon: mdi:current-ac
    unit_of_measurement: "A"
    lambda: |-
      return id(current_1).state + id(current_2).state;
    update_interval: ${measurement_interval}

time:
  - platform: sntp
    id: my_time