packages:
  common: !include common.yaml

esp32_improv:
  authorizer: none
  wifi_timeout: 5min

esphome:
  platformio_options:
    board_build.flash_mode: dio

esp32:
  board: esp32-c3-devkitm-1
  framework:
    type: esp-idf

#Disable logging/UART
logger:
# level: NONE
  baud_rate: 0

i2c:
  sda: GPIO6
  scl: GPIO7
  scan: true
  id: I2C

sensor:
  - platform: internal_temperature
    name: "Interní teplota"
    accuracy_decimals: 2
    update_interval: 30s
    
binary_sensor:
  - platform: gpio
    pin: 2
    name: "Tlačítko 1"
    filters:
      - invert:
  - platform: gpio
    pin: 8
    name: "Tlačítko 2"
    filters:
      - invert:
  - platform: gpio
    pin: 9
    name: "Tlačítko 3"
    filters:
      - invert:

output:
  - platform: ledc
    pin: GPIO5
    frequency: 19531Hz
    id: LED_channel_1
  - platform: ledc
    pin: GPIO4
    frequency: 19531Hz
    id: LED_channel_2
  - platform: ledc
    pin: GPIO1
    frequency: 19531Hz
    id: LED_channel_3
  - platform: ledc
    pin: GPIO0
    frequency: 19531Hz
    id: LED_channel_4
  - platform: ledc
    pin: GPIO3
    frequency: 19531Hz
    id: LED_channel_5

  - platform: template
    id: LED_channel_1_3
    type: float
    write_action:
      - output.set_level:
          id: LED_channel_1
          level: !lambda return state;
      - output.set_level:
          id: LED_channel_3
          level: !lambda return state;

  - platform: template
    id: LED_channel_2_4
    type: float
    write_action:
      - output.set_level:
          id: LED_channel_2
          level: !lambda return state;
      - output.set_level:
          id: LED_channel_4
          level: !lambda return state;

light:
  - platform: cwww
    name: "Světlo"
    icon: mdi:led-strip-variant
    cold_white: LED_channel_1_3
    warm_white: LED_channel_2_4
    cold_white_color_temperature: 6500 K
    warm_white_color_temperature: 2200 K
    # Koriguje minimální jas, čím vyšší hodnota tim menší minimalní jas
    gamma_correct: 1.2
    constant_brightness: true
    restore_mode: ALWAYS_ON

button:
  - platform: template
    name: "Plný jas"
    icon: mdi:weather-sunny-alert
    on_press:
      - output.set_level:
          id: LED_channel_1_3
          level: 100%
      - output.set_level:
          id: LED_channel_2_4
          level: 100%


