packages:
  common: !include common.yaml


esp8266:
  board: esp8285
  restore_from_flash: true


button:
  - platform: factory_reset
    name: Resetování do továrního nastavení
    id: reset


output:
  - platform: gpio
    pin: GPIO12
    id: relay


light:
  - platform: status_led
    name: "${name} stavová LED"
    icon: mdi:led-on
    pin:
      number: GPIO4
      inverted: true

  - platform: binary
    name: "${name} světlo"
    icon: mdi:ceiling-light-multiple
    id: mini_relay
    output: relay
    restore_mode: RESTORE_DEFAULT_OFF


binary_sensor:
  # Wired switch
  - platform: gpio
    name: "${name} vypínač"
    icon: mdi:light-switch
    id: the_switch
    pin:
      number: GPIO14
      mode: INPUT_PULLUP
      inverted: true
    on_state:
      - light.toggle: mini_relay

    on_multi_click:
      - timing:
          - ON for at most 0.5s
          - OFF for at most 0.5s
          - ON for at most 0.5s
          - OFF for at most 0.5s
          - ON for at most 0.5s
          - OFF for at most 0.5s
          - ON for at most 0.5s
          - OFF for at most 0.5s
          - ON for at most 0.5s
          - OFF for at most 0.5s
        then:
          - button.press: reset

  # Button on mini switch
  - platform: gpio
    name: "${name} tlačítko"
    icon: mdi:gesture-tap-button
    pin:
      number: GPIO3
      mode: INPUT_PULLUP
      inverted: true
    on_multi_click:
      - timing:
          - ON for at most 1s
          - OFF for at least 0.2s
        then:
          - light.toggle: mini_relay
      - timing:
          - ON for at least 4s
        then:
          - button.press: reset

  - platform: status
    name: "${name} stav"


time:
  - platform: sntp
    id: my_time  
