binary_sensor:
  - platform: gpio
    pin: ${button_pin}
    name: "${button_name}"
    filters:
      - invert:
      - delayed_on_off: 20ms
    on_multi_click:
      - timing:
          - ON for at most 400ms
          - OFF for at least 210ms
        then:
          - lambda: |-
              auto &values = id(${light_id}).current_values;
              if (values.is_on()) {
                id(${light_id}).turn_off().perform();
                return;
              }
              float kelvin = id(ha_color_temperature).state;
              float brightness = id(ha_brightness).state;
              id(${light_id}).turn_on()
                  .set_color_temperature(std::isnan(kelvin) ? values.get_color_temperature() : 1000000.0f / kelvin)
                  .set_brightness(std::isnan(brightness) ? values.get_brightness() : brightness / 100.0f)
                  .perform();
      - timing:
          - ON for at most 400ms
          - OFF for at most 200ms
          - ON for at most 400ms
          - OFF for at least 200ms
        then:
          - lambda: |-
              float min_m = id(${light_id}).get_traits().get_min_mireds();
              float max_m = id(${light_id}).get_traits().get_max_mireds();
              float target = id(${light_id}).current_values.get_color_temperature() < (min_m + max_m) / 2.0f ? max_m : min_m;
              id(${light_id}).turn_on().set_color_temperature(target).perform();
      - timing:
          - ON for at least 500ms
        then:
          - lambda: |-
              bool is_bright = id(${light_id}).current_values.is_on() && id(${light_id}).current_values.get_brightness() > 0.99f;
              id(${light_id}).turn_on().set_brightness(is_bright ? 0.01f : 1.0f).perform();
