blueprint:
  name: Upozornění na vypnutá polohová oprávnění
  description: >-
    Odesílá akci a uchovává seznam zařízení bez povolení polohových dat.
    Funguje pouze pro iOS zařízení (sensor.location_permission je iOS-only).
  domain: automation
  author: Jakub Znamenáček
  homeassistant:
    min_version: "2024.10.0"
  input:
    trigger_action:
      name: Akce při vypnutí polohových oprávnění
      description: Vyberte akci, která se má vykonat, pokud některé zařízení nemá povolena polohová data.
      selector:
        action: {}

    notify_time:
      name: Čas denního upozornění
      description: Kdy má být odesláno pravidelné denní upozornění.
      default: "21:00:00"
      selector:
        time: {}

variables:
  devices: >-
    {% set ns = namespace(devices=[]) %}
    {% set ignored_states = ['Authorized Always', 'unavailable', 'unknown'] %}
    {% for entity in integration_entities('mobile_app') | select('search', 'location_permission') %}
      {% if states(entity) not in ignored_states %}
        {% set name = device_attr(device_id(entity), 'name_by_user') or device_attr(device_id(entity), 'name') %}
        {% set ns.devices = ns.devices + [name] %}
      {% endif %}
    {% endfor %}
    {{ ns.devices }}

triggers:
  - trigger: template
    value_template: >-
      {{ integration_entities('mobile_app') | select('search', 'location_permission')
      | map('states') | reject('eq', 'Authorized Always')
      | reject('eq', 'unavailable') | reject('eq', 'unknown') | list | count > 0 }}
    for: "00:00:30"
  - trigger: time
    at: !input notify_time

conditions:
  - condition: template
    value_template: "{{ devices | count > 0 }}"

actions: !input trigger_action

mode: single